var states = {
        'AK': {'region': 'West', 'name': 'Alaska'},
        'AL': {'region': 'South', 'name': 'Alabama'},
        'AR': {'region': 'South', 'name': 'Arkansas'},
        'AS': {'region': 'West', 'name': 'American Samoa'},
        'AZ': {'region': 'West', 'name': 'Arizona'},
        'CA': {'region': 'West Coast', 'name': 'California'},
        'CO': {'region': 'West', 'name': 'Colorado'},
        'CT': {'region': 'Northeast', 'name': 'Connecticut'},
        'DC': {'region': 'West', 'name': 'District of Columbia'},
        'DE': {'region': 'South', 'name': 'Delaware'},
        'FL': {'region': 'South', 'name': 'Florida'},
        'GA': {'region': 'South', 'name': 'Georgia'},
        'GU': {'region': 'West', 'name': 'Guam'},
        'HI': {'region': 'West', 'name': 'Hawaii'},
        'IA': {'region': 'Midwest', 'name': 'Iowa'},
        'ID': {'region': 'West', 'name': 'Idaho'},
        'IL': {'region': 'Midwest', 'name': 'Illinois'},
        'IN': {'region': 'Midwest', 'name': 'Indiana'},
        'KS': {'region': 'Midwest', 'name': 'Kansas'},
        'KY': {'region': 'South', 'name': 'Kentucky'},
        'LA': {'region': 'South', 'name': 'Louisiana'},
        'MA': {'region': 'Northeast', 'name': 'Massachusetts'},
        'MD': {'region': 'South', 'name': 'Maryland'},
        'ME': {'region': 'Northeast', 'name': 'Maine'},
        'MI': {'region': 'Midwest', 'name': 'Michigan'},
        'MN': {'region': 'Midwest', 'name': 'Minnesota'},
        'MO': {'region': 'Midwest', 'name': 'Missouri'},
        'MP': {'region': 'West', 'name': 'Northern Mariana Islands'},
        'MS': {'region': 'South', 'name': 'Mississippi'},
        'MT': {'region': 'West', 'name': 'Montana'},
        'NA': {'region': 'West', 'name': 'National'},
        'NC': {'region': 'South', 'name': 'North Carolina'},
        'ND': {'region': 'Midwest', 'name': 'North Dakota'},
        'NE': {'region': 'Midwest', 'name': 'Nebraska'},
        'NH': {'region': 'Northeast', 'name': 'New Hampshire'},
        'NJ': {'region': 'Northeast', 'name': 'New Jersey'},
        'NM': {'region': 'West', 'name': 'New Mexico'},
        'NV': {'region': 'West', 'name': 'Nevada'},
        'NY': {'region': 'Northeast', 'name': 'New York'},
        'OH': {'region': 'Midwest', 'name': 'Ohio'},
        'OK': {'region': 'South', 'name': 'Oklahoma'},
        'OR': {'region': 'West Coast', 'name': 'Oregon'},
        'PA': {'region': 'Northeast', 'name': 'Pennsylvania'},
        'PR': {'region': 'West', 'name': 'Puerto Rico'},
        'RI': {'region': 'Northeast', 'name': 'Rhode Island'},
        'SC': {'region': 'South', 'name': 'South Carolina'},
        'SD': {'region': 'Midwest', 'name': 'South Dakota'},
        'TN': {'region': 'South', 'name': 'Tennessee'},
        'TX': {'region': 'South', 'name': 'Texas'},
        'UT': {'region': 'West', 'name': 'Utah'},
        'VA': {'region': 'South', 'name': 'Virginia'},
        'VI': {'region': 'West', 'name': 'Virgin Islands'},
        'VT': {'region': 'Northeast', 'name': 'Vermont'},
        'WA': {'region': 'West Coast', 'name': 'Washington'},
        'WI': {'region': 'Midwest', 'name': 'Wisconsin'},
        'WV': {'region': 'South', 'name': 'West Virginia'},
        'WY': {'region': 'West', 'name': 'Wyoming'}
}
